
// PEOPLE ACTIONS
export const PEOPLE_INIT_LOAD = "PEOPLE_INIT_LOAD";
export const PEOPLE_CHANGE_PAGE = "PEOPLE_CHANGE_PAGE";

// PLANET ACTIONS
export const PLANET_INIT_LOAD = "PLANET_INIT_LOAD";
export const PLANET_CHANGE_PAGE = "PLANET_CHANGE_PAGE";

// STARSHIP ACTIONS
export const STARSHIP_INIT_LOAD = "STARSHIP_INIT_LOAD";
export const STARSHIP_CHANGE_PAGE = "STARSHIP_CHANGE_PAGE";