
export const PEOPLE_INIT_LOAD = "PEOPLE_INIT_LOAD";

export const PEOPLE_CHANGE_PAGE = "PEOPLE_CHANGE_PAGE";

export const PLANET_INIT_LOAD = "PLANET_INIT_LOAD";

export const PLANET_CHANGE_PAGE = "PLANET_CHANGE_PAGE";